language: objective-c
xcode_project: SQLiteLib.xcodeproj

# Disable the default Travis-CI submodule logic
git:
  submodules: false

## Travis-CI doesn’t currently support automatically expanding osx_image
## into the build matrix.
##
## see: https://github.com/travis-ci/travis-ci/issues/7587
##
#
#gemfile: .ci/Gemfile.travis
#
#osx_image:
#  - xcode7.3
#  - xcode8.3
#
#env:
#  - DESTINATION="platform=macOS,arch=x86_64"
#  - DESTINATION="platform=macOS,arch=i386"
#  - DESTINATION="generic/platform=iOS"
#  - DESTINATION="generic/platform=watchOS"
#  - DESTINATION="generic/platform=tvOS"
#  - DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=10.3.1"

matrix:
  include:

    ###################################
    ### Xcode 7.3 on macOS 10.11

    - os: osx
      osx_image: xcode7.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=OS X"
    - os: osx
      osx_image: xcode7.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=iOS"
    - os: osx
      osx_image: xcode7.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=watchOS"
    - os: osx
      osx_image: xcode7.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=tvOS"
    - os: osx
      osx_image: xcode7.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=9.3"

    ###################################
    ### Xcode 8.3.3 on macOS 10.12

    - os: osx
      osx_image: xcode8.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=macOS"
    - os: osx
      osx_image: xcode8.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=iOS"
    - os: osx
      osx_image: xcode8.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=watchOS"
    - os: osx
      osx_image: xcode8.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=tvOS"
    - os: osx
      osx_image: xcode8.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=iOS Simulator,name=iPhone 6s,OS=10.3.1"
    - os: osx
      osx_image: xcode8.3
      gemfile: .ci/Gemfile.travis
      env:
        - SDK="iphoneos"

    ###################################
    ### Xcode 9.4.1 on macOS 10.13

    - os: osx
      osx_image: xcode9.4
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=macOS"
    - os: osx
      osx_image: xcode9.4
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=iOS"
    - os: osx
      osx_image: xcode9.4
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=watchOS"
    - os: osx
      osx_image: xcode9.4
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=tvOS"
    - os: osx
      osx_image: xcode9.4
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.4"
    - os: osx
      osx_image: xcode9.4
      gemfile: .ci/Gemfile.travis
      env:
        - SDK="iphoneos"

    ###################################
    ### Xcode 10.3 on macOS 10.14

    - os: osx
      osx_image: xcode10.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=macOS"
    - os: osx
      osx_image: xcode10.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=iOS"
    - os: osx
      osx_image: xcode10.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=watchOS"
    - os: osx
      osx_image: xcode10.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=tvOS"
    - os: osx
      osx_image: xcode10.3
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.4"
    - os: osx
      osx_image: xcode10.3
      gemfile: .ci/Gemfile.travis
      env:
        - SDK="iphoneos"

    ###################################
    ### Xcode 11.2.1 on macOS 10.14

    - os: osx
      osx_image: xcode11.2
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=macOS"
    - os: osx
      osx_image: xcode11.2
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=iOS"
    - os: osx
      osx_image: xcode11.2
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=watchOS"
    - os: osx
      osx_image: xcode11.2
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="generic/platform=tvOS"
    - os: osx
      osx_image: xcode11.2
      gemfile: .ci/Gemfile.travis
      env:
        - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=13.2.2"
    - os: osx
      osx_image: xcode11.2
      gemfile: .ci/Gemfile.travis
      env:
        - SDK="iphoneos"

script:
  - cd .ci
  - make test_build
