language: objective-c
xcode_project: SQLiteLib.xcodeproj

# Disable the default Travis-CI submodule logic
git:
  submodules: false

gemfile: .ci/Gemfile.travis

xcode_sdk:
  - xcode7.3
  - xcode8.3

env:
  - DESTINATION: platform=macOS,arch=x86_64
  - DESTINATION: platform=macOS,arch=i386
  - DESTINATION: generic/platform=iOS
  - DESTINATION: generic/platform=watchOS
  - DESTINATION: generic/platform=tvOS
  - DESTINATION: platform=iOS Simulator,name=iPhone 6s,OS=10.3

script:
  - cd .ci
  - make test_build
